# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: sl2017@alco.dk
  admin_password: changeme
  domain_name: localhost:3000
  secret_key_base: 0a934fc3c08b14a67611f61dcee5ecc00002503e36a0366ce7ba94c5ec7b25c5f607d163655258f7cf72421e970ac226c2f2c3987eae5b47ed25fc39ed3e3ae7
  smtp_host:        <%= ENV["SMTP_HOST"] %>
  smtp_port:        <%= ENV["SMTP_PORT"] %>
  smtp_domain_name: <%= ENV["SMTP_DOMAIN_NAME"] %>
  smtp_user:        <%= ENV["SMTP_USER"] %>
  smtp_password:    <%= ENV["SMTP_PASSWORD"] %>
  imap_mail_server: pbox.dk
  imap_user_name: sl2017@alco.dk
  imap_user_password: sl2017!job
  imap_source_mailbox: INBOX
  imap_archive_mailbox: archive





test:
  domain_name: example.com
  secret_key_base: 7c49bff115d6ad1cb30aa52821584519ebb9a08387fdca4687462da263dcf68141504b55550b4ef0b3f4f226cf4eae810ac1add77da81e0225add0b4fd0d7b62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base:  <%= ENV["SECRET_KEY_BASE"] %>
  smtp_host:        <%= ENV["SMTP_HOST"] %>
  smtp_port:        <%= ENV["SMTP_PORT"] %>
  smtp_domain_name: <%= ENV["SMTP_DOMAIN_NAME"] %>
  smtp_user:        <%= ENV["SMTP_USER"] %>
  smtp_password:    <%= ENV["SMTP_PASSWORD"] %>
